from datetime import datetime
from typing import Any, Optional
from pydantic import BaseModel, Field


class HazardPoint(BaseModel):
    """
    Common schema for all ingested hazard sources (L1 output).
    Every service — FIRMS, Env Canada, AQI, road closures — normalises into this.
    L2 consumes a list of these to generate hazard polygons.
    """

    lat:                  float
    lon:                  float
    hazard_type:          str                        # "wildfire" | "smoke" | "road_closure" | "wind"
    severity:             str                        # "low" | "moderate" | "high"
    source:               str                        # "NASA FIRMS" | "Env Canada" | "AQI" | "AB511"
    timestamp:            datetime = Field(default_factory=datetime.utcnow)
    confidence:           Optional[float] = None     # 0.0 – 1.0, None if source doesn't provide it
    spatial_impact_radius: Optional[float] = None    # kilometres — used by L2 to draw smoke polygons
    metadata:             dict[str, Any] = {}        # source-specific fields (frp_mw, aqi_index, etc.)


class WindVector(BaseModel):
    """
    Normalised wind reading from Environment Canada stations.
    L2 uses this to calculate smoke drift direction and speed.
    """

    lat:           float
    lon:           float
    station_id:    str
    speed_kmh:     float
    direction_deg: float                             # 0–360, direction wind is coming FROM
    gusts_kmh:     Optional[float] = None
    timestamp:     datetime = Field(default_factory=datetime.utcnow)


class RouteSegment(BaseModel):
    """
    A decoded segment of a Google Directions polyline.
    L3 scores each segment against the hazard field at predicted arrival time.
    """

    index:            int
    start_lat:        float
    start_lon:        float
    end_lat:          float
    end_lon:          float
    distance_km:      float
    travel_time_min:  float
    cumulative_time_min: float                       # time from trip start — used for hazard field lookup


class ScoredSegment(RouteSegment):
    """
    RouteSegment extended with L3 risk scoring output.
    L4 consumes a list of these to decide where to generate avoidance waypoints.
    """

    risk_score:    float                             # 0.0 – 1.0
    hazard_type:   Optional[str] = None             # dominant hazard on this segment
    aqi_estimate:  Optional[float] = None


class HazardPolygon(BaseModel):
    """
    A time-stamped smoke/hazard zone generated by L2.
    Stored as a GeoJSON-compatible coordinate ring.
    """

    hazard_type:  str
    severity:     str
    valid_at:     datetime                           # the future time this polygon is valid for
    coordinates:  list[list[float]]                  # [[lon, lat], ...] closed ring — GeoJSON order
    source_fire:  Optional[str] = None              # FIRMS fire ID if applicable


class OptimizedRoute(BaseModel):
    """
    L4 output — the final rerouted result returned to the frontend.
    """

    origin:              str
    destination:         str
    waypoints:           list[dict[str, float]]      # [{"lat": ..., "lon": ...}, ...]
    segments:            list[ScoredSegment]
    max_risk_score:      float
    total_distance_km:   float
    total_time_min:      float
    rerouted:            bool
    briefing:            Optional[str] = None        # Gemini-generated natural language summary